### ISSUE TITLE
error with show preference

### ISSUE THREAD

**Issue by Arraxx** [fluid-project/infusion-docs#156]
When we go to a new page it shows show display preference for some time but after it disappears and only show preference is shown 
![ezgif com-video-to-gif(4)](https://user-images.githubusercontent.com/54955755/75570988-4fd59d00-5a7e-11ea-9c0e-ed94869bd19d.gif)

i would like to take this issue

**Comment by coderbabu10** [comment]
@jhung @jobara

**Comment by jobara** [comment]
It looks like this is a combination of the page rendering slowly (slow internet connection or browser rendering slowly) and the template having a value of "show display preferences" which is showing by default.

**Comment by coderbabu10** [comment]
so we can change it by making 'show display preference' or 'show preference' permanent

**Comment by jobara** [comment]
Not sure what you mean by permanent. The text is updated from UI Options to support localization and other text related changes. Changing the text in the template would alleviate the issue because it would just be changed back to itself, but the problem of slow rendering should be investigated more.

**Comment by greatislander** [comment]
I've changed the default text to "Show Preferences" in #190 so that the button won't change after it's instantiated.
