### ISSUE TITLE
unlikely button spotted 

### ISSUE THREAD

**Issue by Pratik10100** [fluid-project/infusion-docs#171]
![Screenshot 2020-03-13 at 3 02 28 PM](https://user-images.githubusercontent.com/48441961/76609093-cec9db80-653c-11ea-9d7e-62a172bea2ab.png)

**Comment by Pratik10100** [comment]
I am working on this issue.

**Comment by jobara** [comment]
@Pratik10100 I'm not sure what the issue you are reporting is. Please include a detailed description of the issue, including at least the following: written description describing the issue, written description of what should be improved and why, detailed steps to reproduce, which browser and platform the issue was found on. Also when adding images, please make sure that the descriptions are enough to be understood without the image being viewed. It may be the case that someone reading this issue cannot perceive the image. For me, I am able to perceive the image, but am still not sure what I'm supposed to be looking at.
